spring.application.name=aqua-app

# Database URL (Format: jdbc:postgresql://HOST:PORT/DATABASE_NAME)
spring.datasource.url='hidden????'

# Credentials
# spring.datasource.username=neondb_owner
# spring.datasource.password=npg_2tjxM8QcLIfH

# Hibernate Configuration
# 'update' will automatically create/update tables to match your Java code
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect